[autoexec]
@echo off
mount c: .
c:
path c:\watcom\binw;%path%
set include=c:\watcom\h
set watcom=c:\watcom
set edpath=c:\watcom\eddat
set wipfc=c:\watcom\wipfc
if not exist "c:\tmp\nul" mkdir c:\tmp
call build

[cpu]
cycles=max
