name: Test-Build
on:
  push:
    branches:
      - 4_17
jobs:
  for-hosted:
    strategy:
      fail-fast: false
      matrix:
        os:
        - 'macos-10.15'
        - 'macos-11'
        - 'macos-12'
        - 'ubuntu-22.04'
        - 'ubuntu-20.04'
        - 'ubuntu-18.04'
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "event=${{ github.event_name }} runner=${{ runner.os }} os=${{ matrix.os }} branch=${{ github.ref }} repo=${{ github.repository }}."
      - uses: actions/checkout@v3
      - run: ./testbuild.sh --sudo-preinstall
      - run: echo "status=${{ job.status }}."
      - uses: actions/upload-artifact@v3
        with:
          path: DIST
  for-containers:
    strategy:
      fail-fast: false
      matrix:
        os:
        - 'debian:9'
        - 'debian:11'
        - 'debian:testing'
        - 'alpine:3.9'
        - 'alpine:3.14'
        - 'centos:7'
        - 'fedora:30'
        - 'fedora:34'
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    steps:
      - run: echo "event=${{ github.event_name }} runner=${{ runner.os }} os=${{ matrix.container }} branch=${{ github.ref }} repo=${{ github.repository }}."
      - uses: actions/checkout@v3
      - run: ./testbuild.sh --preinstall
      - if: startsWith(matrix.container, 'centos:') || startsWith(matrix.container, 'fedora:')
        run: rpm -i $HOME/rpmbuild/RPMS/x86_64/jove-4*.rpm
      - run: echo "status=${{ job.status }}."
      - uses: actions/upload-artifact@v3
        with:
          path: DIST
