name: Test Build
on: [push]
jobs:
  Test build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "branch ${{ github.ref }} repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - name: Test
        run: |
          apt-get install -y make ctags zip ncurses-dev groff && cd ${{ github.workspace }} && make travis
      - run: echo "This job's status is ${{ job.status }}."
