name: Test-Build
on:
  push:
    branches:
      - 4_17
jobs:
  for-hosted:
    strategy:
      matrix:
        os:
        - 'macos-10.15'
        - 'macos-11'
        - 'macos-12'
        - 'ubuntu-22.04'
        - 'ubuntu-20.04'
        - 'ubuntu-18.04'
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "event=${{ github.event_name }} runner=${{ runner.os }} os=${{ matrix.os }} branch=${{ github.ref }} repo=${{ github.repository }}."
      - name: HostedCheckout
        uses: actions/checkout@v3
      - name: HostedMacPrep
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew install make ctags zip ncurses
      - name: HostedUbuPrep
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y gcc make pkg-config ncurses-dev exuberant-ctags zip groff
      - name: HostedTestBuild
        run: |
          ./testbuild.sh
      - run: echo "status=${{ job.status }}."
  for-containers:
    strategy:
      matrix:
        container:
        - 'debian:9'
        - 'debian:11'
        - 'debian:testing'
        - 'alpine:3.9'
        - 'alpine:3.14'
        - 'centos:7'
        - 'fedora:30'
        - 'fedora:34'
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - run: echo "event=${{ github.event_name }} os=${{ runner.os }} container=${{ matrix.container }} branch=${{ github.ref }} repo=${{ github.repository }}."
      - name: ContainerCheckout
        uses: actions/checkout@v3
      - name: ContainerAptPrep
        if: startsWith(matrix.container, 'debian:')
        run: |
          apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y gcc make pkg-config ncurses-dev exuberant-ctags zip groff
      - name: ContainerApkPrep
        if: startsWith(matrix.container, 'alpine:')
        run: |
          apk update && apk add gcc make pkgconfig ncurses-dev ctags zip groff 
      - name: ContainerRpmPrep
        if: startsWith(matrix.container, 'centos:') || startsWith(matrix.container, 'fedora:')
        run: |
          yum install -y make gcc ncurses-devel zip groff ctags rpm-build
      - name: ContainerTestBuild
        run: |
          ./testbuild.sh
      - name: ContainerRpmBuild
        if: startsWith(matrix.container, 'centos:') || startsWith(matrix.container, 'fedora:')
        run: |
          make rpm && rpm -i $HOME/rpmbuild/RPMS/x86_64/jove-4*.rpm
      - run: echo "status=${{ job.status }}."
