name: Test-Build
on:
  push:
    branches:
      - 4_17
jobs:
  for-apt-distros:
    strategy:
      matrix:
        container:
        - 'ubuntu:18.04'
        - 'ubuntu:20.04'
        - 'ubuntu:devel'
        - 'debian:11'
        - 'debian:testing'
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - run: echo "event=${{ github.event_name }} os=${{ runner.os }} branch=${{ github.ref }} repo=${{ github.repository }}."
      - name: Checkout
        uses: actions/checkout@v3
      - name: TestBuild
        run: |
          apt-get update && apt-get install -y gcc make exuberant-ctags zip ncurses-dev groff && ./testbuild.sh
      - run: echo "status=${{ job.status }}."
