name: Test-Build
on: [push]
jobs:
  apt-distros:
    strategy:
      matrix:
        container:
        - 'ubuntu:18.04'
        - 'ubuntu:20.04'
        - 'ubuntu:devel'
        - 'debian:11'
        - 'debian:testing'
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - run: echo "event ${{ github.event_name }} os ${{ runner.os }} ${{ matrix.os }}"
      - run: echo "branch ${{ github.ref }} repo ${{ github.repository }}."
      - name: checkout
        uses: actions/checkout@v3
      - name: test
        run: |
          apt-get update && apt-get install -y gcc make exuberant-ctags zip ncurses-dev groff && make travis
      - run: echo "status ${{ job.status }}."
