name: Test-Build
on:
  push:
    branches:
      - 4_17
jobs:
  for-hosted:
    strategy:
      fail-fast: false
      matrix:
        os:
        - 'macos-11'
        - 'macos-12'
        - 'macos-13'
        - 'ubuntu-22.04'
        - 'ubuntu-20.04'
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "event=${{ github.event_name }} runner=${{ runner.os }} os=${{ matrix.os }} branch=${{ github.ref }} repo=${{ github.repository }}."
      - uses: actions/checkout@v3
      - run: SUDO=sudo ./testbuild.sh --preinstall
      - run: echo "status=${{ job.status }}."
      - uses: actions/upload-artifact@v3
        with:
          path: DIST
  for-containers:
    strategy:
      fail-fast: false
      matrix:
        os:
        - 'debian:8'
        - 'debian:9'
        - 'debian:11'
        - 'debian:testing'
        - 'alpine:3.9'
        - 'alpine:latest'
        - 'centos:7'
        - 'rockylinux:9'
        - 'fedora:30'
        - 'fedora:latest'
        - 'archlinux:latest'
        - 'gentoo/stage3:latest'
        - 'ubuntu/16.04'
        - 'ubuntu/18.04'
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    steps:
      - run: echo "event=${{ github.event_name }} runner=${{ runner.os }} os=${{ matrix.container }} branch=${{ github.ref }} repo=${{ github.repository }}."
      - uses: actions/checkout@v3
      - run: ./testbuild.sh --preinstall
      - run: echo "status=${{ job.status }}."
      - uses: actions/upload-artifact@v3
        with:
          path: DIST
